configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/assembly.smk"
include: "rules/loci.smk"

rule all:
    input:
        "results/00-qc/multiqc/multiqc_report.html",
        "results/01-assembly/qc/contig_lengths.csv",
        f"results/04-uce-fastas/exploded/{dataset}.contig_lengths.csv"
